version: "{build}"

os: Visual Studio 2015

clone_depth: 50

environment:
  matrix:
    # Visual Studio 2015 64bit
    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  machine: amd64
install:
  - cinst winflexbison
  - set LIB=%LIB%;..\mruby-imgtype
  - set PATH=%PATH%;..\mruby-imgtype
init:
  - call "%visualcpp%" %machine%
  - echo %machine%
  - set YACC=win_bison
build_script:
 - cd ..
 - git clone https://github.com/mruby/mruby.git
 - cd mruby
 - set MRUBY_CONFIG=..\mruby-imgtype\appveyor_config.rb
 - rake all test
